--------------------------------------------------------
--  DDL for Table TBL_MEMBER
--------------------------------------------------------

  CREATE TABLE "CYS"."TBL_MEMBER" 
   (	"USERID" VARCHAR2(20 BYTE), 
	"USERNAME" VARCHAR2(20 BYTE), 
	"USERPASSWD" VARCHAR2(20 BYTE), 
	"PHONENUMBER" VARCHAR2(30 BYTE), 
	"ZIP" NUMBER, 
	"BIRTHDAY" NUMBER, 
	"ADDR1" VARCHAR2(50 BYTE), 
	"ADDR2" VARCHAR2(50 BYTE), 
	"PASSWDQ" VARCHAR2(50 BYTE), 
	"PASSWDA" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"AUTHORITY" NUMBER, 
	"REGDATE" DATE DEFAULT sysdate
   );
--------------------------------------------------------
--  Constraints for Table TBL_MEMBER
--------------------------------------------------------

  ALTER TABLE "CYS"."TBL_MEMBER" ADD PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CYS"."TBL_MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_MEMBER" MODIFY ("PASSWDA" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_MEMBER" MODIFY ("PASSWDQ" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_MEMBER" MODIFY ("ADDR2" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_MEMBER" MODIFY ("ADDR1" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_MEMBER" MODIFY ("BIRTHDAY" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_MEMBER" MODIFY ("ZIP" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_MEMBER" MODIFY ("PHONENUMBER" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_MEMBER" MODIFY ("USERPASSWD" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_MEMBER" MODIFY ("USERNAME" NOT NULL ENABLE);





--------------------------------------------------------
--  DDL for Table TBL_ADVERTISE
--------------------------------------------------------

  CREATE TABLE "CYS"."TBL_ADVERTISE" 
   (	"ADNUM" NUMBER, 
	"ADNAME" VARCHAR2(50 BYTE), 
	"ADDES" CLOB, 
	"ADIMG" VARCHAR2(200 BYTE), 
	"REGDATE" DATE DEFAULT sysdate, 
	"ADTHUMBIMG" VARCHAR2(200 BYTE)
   );
--------------------------------------------------------
--  Constraints for Table TBL_ADVERTISE
--------------------------------------------------------

  ALTER TABLE "CYS"."TBL_ADVERTISE" ADD PRIMARY KEY ("ADNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CYS"."TBL_ADVERTISE" MODIFY ("ADNAME" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_ADVERTISE" MODIFY ("ADNUM" NOT NULL ENABLE);
  
  
  
  

--------------------------------------------------------
--  DDL for Table TBL_BOARD
--------------------------------------------------------

  CREATE TABLE "CYS"."TBL_BOARD" 
   (	"BNO" NUMBER, 
	"TITLE" VARCHAR2(100 BYTE), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"WRITER" VARCHAR2(20 BYTE), 
	"REGDATE" DATE DEFAULT SYSDATE, 
	"HIT" NUMBER DEFAULT 0, 
	"BIMG" VARCHAR2(200 BYTE), 
	"BTHUMBIMG" VARCHAR2(200 BYTE)
   );
--------------------------------------------------------
--  Constraints for Table TBL_BOARD
--------------------------------------------------------

  ALTER TABLE "CYS"."TBL_BOARD" ADD PRIMARY KEY ("BNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CYS"."TBL_BOARD" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_BOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_BOARD" MODIFY ("BNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TBL_BOARD
--------------------------------------------------------

  ALTER TABLE "CYS"."TBL_BOARD" ADD CONSTRAINT "BOARD_WRITER" FOREIGN KEY ("WRITER")
	  REFERENCES "CYS"."TBL_MEMBER" ("USERID") ON DELETE CASCADE ENABLE;
      
      
      
      
      
      
      

--------------------------------------------------------
--  DDL for Table TBL_BOARD_REPLY
--------------------------------------------------------

  CREATE TABLE "CYS"."TBL_BOARD_REPLY" 
   (	"BNO" NUMBER, 
	"RNO" NUMBER, 
	"CONTENT" VARCHAR2(1000 BYTE), 
	"WRITER" VARCHAR2(20 BYTE), 
	"REGDATE" DATE DEFAULT sysdate
   );
--------------------------------------------------------
--  Constraints for Table TBL_BOARD_REPLY
--------------------------------------------------------

  ALTER TABLE "CYS"."TBL_BOARD_REPLY" ADD PRIMARY KEY ("BNO", "RNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CYS"."TBL_BOARD_REPLY" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_BOARD_REPLY" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_BOARD_REPLY" MODIFY ("RNO" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_BOARD_REPLY" MODIFY ("BNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TBL_BOARD_REPLY
--------------------------------------------------------

  ALTER TABLE "CYS"."TBL_BOARD_REPLY" ADD CONSTRAINT "REPLY_BNO" FOREIGN KEY ("BNO")
	  REFERENCES "CYS"."TBL_BOARD" ("BNO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "CYS"."TBL_BOARD_REPLY" ADD CONSTRAINT "REPLY_WRITER" FOREIGN KEY ("WRITER")
	  REFERENCES "CYS"."TBL_MEMBER" ("USERID") ON DELETE CASCADE ENABLE;







--------------------------------------------------------
--  DDL for Table TBL_CART
--------------------------------------------------------

  CREATE TABLE "CYS"."TBL_CART" 
   (	"CARTNUM" NUMBER, 
	"USERID" VARCHAR2(50 BYTE), 
	"ITEMNUM" VARCHAR2(20 BYTE), 
	"CARTSTOCK" NUMBER, 
	"REGDATE" DATE DEFAULT sysdate
   );
--------------------------------------------------------
--  Constraints for Table TBL_CART
--------------------------------------------------------

  ALTER TABLE "CYS"."TBL_CART" ADD PRIMARY KEY ("CARTNUM", "USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CYS"."TBL_CART" MODIFY ("CARTSTOCK" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_CART" MODIFY ("ITEMNUM" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_CART" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_CART" MODIFY ("CARTNUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TBL_CART
--------------------------------------------------------

  ALTER TABLE "CYS"."TBL_CART" ADD CONSTRAINT "CART_USERID" FOREIGN KEY ("USERID")
	  REFERENCES "CYS"."TBL_MEMBER" ("USERID") ON DELETE CASCADE ENABLE;








--------------------------------------------------------
--  DDL for Table TBL_INGREDIENT
--------------------------------------------------------

  CREATE TABLE "CYS"."TBL_INGREDIENT" 
   (	"INGNUM" VARCHAR2(20 BYTE), 
	"INGNAME" VARCHAR2(50 BYTE), 
	"INGCATECODE" VARCHAR2(30 BYTE), 
	"INGPRICE" NUMBER, 
	"INGSTOCK" NUMBER, 
	"INGDES" CLOB, 
	"INGIMG" VARCHAR2(200 BYTE), 
	"REGDATE" DATE DEFAULT sysdate, 
	"INGTHUMBIMG" VARCHAR2(200 BYTE), 
	"INGWEIGHT" VARCHAR2(50 BYTE)
   );
--------------------------------------------------------
--  Constraints for Table TBL_INGREDIENT
--------------------------------------------------------

  ALTER TABLE "CYS"."TBL_INGREDIENT" ADD PRIMARY KEY ("INGNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CYS"."TBL_INGREDIENT" MODIFY ("INGWEIGHT" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_INGREDIENT" MODIFY ("INGPRICE" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_INGREDIENT" MODIFY ("INGCATECODE" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_INGREDIENT" MODIFY ("INGNAME" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_INGREDIENT" MODIFY ("INGNUM" NOT NULL ENABLE);





--------------------------------------------------------
--  DDL for Table TBL_ING_REPLY
--------------------------------------------------------

  CREATE TABLE "CYS"."TBL_ING_REPLY" 
   (	"INGNUM" VARCHAR2(20 BYTE), 
	"USERID" VARCHAR2(50 BYTE), 
	"REPNUM" NUMBER, 
	"REPCON" VARCHAR2(2000 BYTE), 
	"REPDATE" DATE DEFAULT sysdate
   );
--------------------------------------------------------
--  Constraints for Table TBL_ING_REPLY
--------------------------------------------------------

  ALTER TABLE "CYS"."TBL_ING_REPLY" ADD PRIMARY KEY ("INGNUM", "REPNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CYS"."TBL_ING_REPLY" MODIFY ("REPCON" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_ING_REPLY" MODIFY ("REPNUM" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_ING_REPLY" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_ING_REPLY" MODIFY ("INGNUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TBL_ING_REPLY
--------------------------------------------------------

  ALTER TABLE "CYS"."TBL_ING_REPLY" ADD CONSTRAINT "ING_REPLY_FK1" FOREIGN KEY ("INGNUM")
	  REFERENCES "CYS"."TBL_INGREDIENT" ("INGNUM") ON DELETE CASCADE ENABLE;
  ALTER TABLE "CYS"."TBL_ING_REPLY" ADD CONSTRAINT "ING_REPLY_FK2" FOREIGN KEY ("USERID")
	  REFERENCES "CYS"."TBL_MEMBER" ("USERID") ON DELETE CASCADE ENABLE;






--------------------------------------------------------
--  DDL for Table TBL_NOTICE
--------------------------------------------------------

  CREATE TABLE "CYS"."TBL_NOTICE" 
   (	"NNO" NUMBER, 
	"TITLE" VARCHAR2(100 BYTE), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"WRITER" VARCHAR2(20 BYTE), 
	"REGDATE" DATE DEFAULT SYSDATE, 
	"HIT" NUMBER DEFAULT 0, 
	"NIMG" VARCHAR2(200 BYTE), 
	"NTHUMBIMG" VARCHAR2(200 BYTE)
   );
--------------------------------------------------------
--  Constraints for Table TBL_NOTICE
--------------------------------------------------------

  ALTER TABLE "CYS"."TBL_NOTICE" ADD PRIMARY KEY ("NNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CYS"."TBL_NOTICE" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_NOTICE" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_NOTICE" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_NOTICE" MODIFY ("NNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TBL_NOTICE
--------------------------------------------------------

  ALTER TABLE "CYS"."TBL_NOTICE" ADD CONSTRAINT "NOTICE_WRITER" FOREIGN KEY ("WRITER")
	  REFERENCES "CYS"."TBL_MEMBER" ("USERID") ON DELETE CASCADE ENABLE;






--------------------------------------------------------
--  DDL for Table TBL_NOTICE_REPLY
--------------------------------------------------------

  CREATE TABLE "CYS"."TBL_NOTICE_REPLY" 
   (	"NNO" NUMBER, 
	"RNO" NUMBER, 
	"CONTENT" VARCHAR2(1000 BYTE), 
	"WRITER" VARCHAR2(20 BYTE), 
	"REGDATE" DATE DEFAULT sysdate
   );
--------------------------------------------------------
--  Constraints for Table TBL_NOTICE_REPLY
--------------------------------------------------------

  ALTER TABLE "CYS"."TBL_NOTICE_REPLY" ADD PRIMARY KEY ("NNO", "RNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CYS"."TBL_NOTICE_REPLY" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_NOTICE_REPLY" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_NOTICE_REPLY" MODIFY ("RNO" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_NOTICE_REPLY" MODIFY ("NNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TBL_NOTICE_REPLY
--------------------------------------------------------

  ALTER TABLE "CYS"."TBL_NOTICE_REPLY" ADD CONSTRAINT "NOTICE_REPLY_NNO" FOREIGN KEY ("NNO")
	  REFERENCES "CYS"."TBL_NOTICE" ("NNO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "CYS"."TBL_NOTICE_REPLY" ADD CONSTRAINT "NOTICE_REPLY_WRITER" FOREIGN KEY ("WRITER")
	  REFERENCES "CYS"."TBL_MEMBER" ("USERID") ON DELETE CASCADE ENABLE;







--------------------------------------------------------
--  DDL for Table TBL_RECIPE
--------------------------------------------------------

  CREATE TABLE "CYS"."TBL_RECIPE" 
   (	"RECIPENUM" VARCHAR2(20 BYTE), 
	"RECIPENAME" VARCHAR2(50 BYTE), 
	"RECIPECATECODE" VARCHAR2(30 BYTE), 
	"RECIPEPRICE" NUMBER, 
	"RECIPESTOCK" NUMBER, 
	"RECIPEDES" CLOB, 
	"RECIPEIMG" VARCHAR2(200 BYTE), 
	"REGDATE" DATE DEFAULT sysdate, 
	"RECIPETHUMBIMG" VARCHAR2(200 BYTE), 
	"INGNAME1" VARCHAR2(50 BYTE), 
	"INGNAME2" VARCHAR2(50 BYTE), 
	"INGNAME3" VARCHAR2(50 BYTE), 
	"INGNAME4" VARCHAR2(50 BYTE), 
	"INGNAME5" VARCHAR2(50 BYTE), 
	"INGNAME6" VARCHAR2(50 BYTE), 
	"INGNAME7" VARCHAR2(50 BYTE), 
	"INGNAME8" VARCHAR2(50 BYTE), 
	"INGNAME9" VARCHAR2(50 BYTE), 
	"INGWEIGHT1" VARCHAR2(20 BYTE), 
	"INGWEIGHT2" VARCHAR2(20 BYTE), 
	"INGWEIGHT3" VARCHAR2(20 BYTE), 
	"INGWEIGHT4" VARCHAR2(20 BYTE), 
	"INGWEIGHT5" VARCHAR2(20 BYTE), 
	"INGWEIGHT6" VARCHAR2(20 BYTE), 
	"INGWEIGHT7" VARCHAR2(20 BYTE), 
	"INGWEIGHT8" VARCHAR2(20 BYTE), 
	"INGWEIGHT9" VARCHAR2(20 BYTE), 
	"INGPRICE1" NUMBER(10,0), 
	"INGPRICE2" NUMBER(10,0), 
	"INGPRICE3" NUMBER(10,0), 
	"INGPRICE4" NUMBER(10,0), 
	"INGPRICE5" NUMBER(10,0), 
	"INGPRICE6" NUMBER(10,0), 
	"INGPRICE7" NUMBER(10,0), 
	"INGPRICE8" NUMBER(10,0), 
	"INGPRICE9" NUMBER(10,0)
   );
--------------------------------------------------------
--  Constraints for Table TBL_RECIPE
--------------------------------------------------------

  ALTER TABLE "CYS"."TBL_RECIPE" ADD PRIMARY KEY ("RECIPENUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CYS"."TBL_RECIPE" MODIFY ("RECIPEPRICE" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_RECIPE" MODIFY ("RECIPECATECODE" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_RECIPE" MODIFY ("RECIPENAME" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_RECIPE" MODIFY ("RECIPENUM" NOT NULL ENABLE);








--------------------------------------------------------
--  DDL for Table TBL_RECIPE_REPLY
--------------------------------------------------------

  CREATE TABLE "CYS"."TBL_RECIPE_REPLY" 
   (	"RECIPENUM" VARCHAR2(20 BYTE), 
	"USERID" VARCHAR2(50 BYTE), 
	"REPNUM" NUMBER, 
	"REPCON" VARCHAR2(2000 BYTE), 
	"REPDATE" DATE DEFAULT sysdate
   );
--------------------------------------------------------
--  Constraints for Table TBL_RECIPE_REPLY
--------------------------------------------------------

  ALTER TABLE "CYS"."TBL_RECIPE_REPLY" ADD PRIMARY KEY ("RECIPENUM", "REPNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CYS"."TBL_RECIPE_REPLY" MODIFY ("REPCON" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_RECIPE_REPLY" MODIFY ("REPNUM" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_RECIPE_REPLY" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_RECIPE_REPLY" MODIFY ("RECIPENUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TBL_RECIPE_REPLY
--------------------------------------------------------

  ALTER TABLE "CYS"."TBL_RECIPE_REPLY" ADD CONSTRAINT "RECIPE_REPLY_FK1" FOREIGN KEY ("RECIPENUM")
	  REFERENCES "CYS"."TBL_RECIPE" ("RECIPENUM") ON DELETE CASCADE ENABLE;
  ALTER TABLE "CYS"."TBL_RECIPE_REPLY" ADD CONSTRAINT "RECIPE_REPLY_FK2" FOREIGN KEY ("USERID")
	  REFERENCES "CYS"."TBL_MEMBER" ("USERID") ON DELETE CASCADE ENABLE;








--------------------------------------------------------
--  DDL for Table TBL_ORDER
--------------------------------------------------------

  CREATE TABLE "CYS"."TBL_ORDER" 
   (	"ORDERID" VARCHAR2(50 BYTE), 
	"USERID" VARCHAR2(50 BYTE), 
	"ORDERREC" VARCHAR2(50 BYTE), 
	"ZIP" NUMBER, 
	"ADDR1" VARCHAR2(50 BYTE), 
	"ADDR2" VARCHAR2(50 BYTE), 
	"ORDERPHONE" VARCHAR2(30 BYTE), 
	"AMOUNT" NUMBER, 
	"ORDERDATE" DATE DEFAULT SYSDATE, 
	"DELIVERY" CHAR(1 BYTE) DEFAULT 'N'
   );
--------------------------------------------------------
--  Constraints for Table TBL_ORDER
--------------------------------------------------------

  ALTER TABLE "CYS"."TBL_ORDER" ADD PRIMARY KEY ("ORDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CYS"."TBL_ORDER" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_ORDER" MODIFY ("ORDERPHONE" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_ORDER" MODIFY ("ADDR2" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_ORDER" MODIFY ("ADDR1" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_ORDER" MODIFY ("ZIP" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_ORDER" MODIFY ("ORDERREC" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_ORDER" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_ORDER" MODIFY ("ORDERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TBL_ORDER
--------------------------------------------------------

  ALTER TABLE "CYS"."TBL_ORDER" ADD CONSTRAINT "TBL_ORDER_USERID" FOREIGN KEY ("USERID")
	  REFERENCES "CYS"."TBL_MEMBER" ("USERID") ON DELETE CASCADE ENABLE;






--------------------------------------------------------
--  DDL for Table TBL_ORDER_DETAILS
--------------------------------------------------------

  CREATE TABLE "CYS"."TBL_ORDER_DETAILS" 
   (	"ORDERDETAILSNUM" NUMBER, 
	"ORDERID" VARCHAR2(50 BYTE), 
	"ITEMNUM" VARCHAR2(20 BYTE), 
	"CARTSTOCK" NUMBER
   );
--------------------------------------------------------
--  Constraints for Table TBL_ORDER_DETAILS
--------------------------------------------------------

  ALTER TABLE "CYS"."TBL_ORDER_DETAILS" ADD PRIMARY KEY ("ORDERDETAILSNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CYS"."TBL_ORDER_DETAILS" MODIFY ("CARTSTOCK" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_ORDER_DETAILS" MODIFY ("ITEMNUM" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_ORDER_DETAILS" MODIFY ("ORDERID" NOT NULL ENABLE);
  ALTER TABLE "CYS"."TBL_ORDER_DETAILS" MODIFY ("ORDERDETAILSNUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TBL_ORDER_DETAILS
--------------------------------------------------------

  ALTER TABLE "CYS"."TBL_ORDER_DETAILS" ADD CONSTRAINT "TBL_ORDER_DETAILS_ORDERID" FOREIGN KEY ("ORDERID")
	  REFERENCES "CYS"."TBL_ORDER" ("ORDERID") ON DELETE CASCADE ENABLE;
      
      
      
      
      
      
      

   CREATE SEQUENCE  "CYS"."ADVERTISE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
   CREATE SEQUENCE  "CYS"."BOARD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
   CREATE SEQUENCE  "CYS"."CART_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
   CREATE SEQUENCE  "CYS"."ING_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
   CREATE SEQUENCE  "CYS"."ING_REPLY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
   CREATE SEQUENCE  "CYS"."NOTICE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
   CREATE SEQUENCE  "CYS"."RECIPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
   CREATE SEQUENCE  "CYS"."RECIPE_REPLY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
   CREATE SEQUENCE  "CYS"."REPLY_SEQ"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
   CREATE SEQUENCE  "CYS"."TBL_ORDER_DETAILS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;

